CREATE DATABASE SMS;
USE SMS;
CREATE TABLE STUDENT_DETAILS(
  Student_ID  VARCHAR(20) NOT NULL ,
  Student_Name VARCHAR(255) NOT NULL ,
  DOB VARCHAR(255) NOT NULL ,
  Gender VARCHAR(10) NOT NULL ,
  Class VARCHAR(20) NOT NULL ,
  School VARCHAR(255) NOT NULL,
  Fee VARCHAR(25) NOT NULL ,
  Admission_Date VARCHAR(255) NOT NULL ,
  Father_Name VARCHAR(255) NOT NULL ,
  Mother_Name VARCHAR(255) NOT NULL ,
  Address VARCHAR(255),
  Contact_Number VARCHAR(255)
);
CREATE TABLE FEEDETAILS(
  Student_ID  VARCHAR(20) NOT NULL ,
  Student_Name VARCHAR(255) NOT NULL ,
  Payment_Date VARCHAR(255) NOT NULL ,
  Month VARCHAR(255) NOT NULL ,
  Amount_Paid VARCHAR(255) NOT NULL ,
  Remaining VARCHAR(255) NOT NULL
);
